### ISSUE TITLE
[내일배움코스/8회차] FE 채용 과제로 배우는 자바스크립트 - [미션1] 레이아웃, 기본 API 요청

### ISSUE THREAD

**Issue by ojj1123** [ojj1123/tip-archive#1]
# [미션1] 레이아웃, 기본 API 요청

### 반응형웹
- [x] 유저가 사용하는 디바이스의 가로 길이에 따라 검색결과의 row 당 column 갯수를 적절히 변경해주어야 합니다.  
  * 992px 이하: 3개
  * 768px 이하: 2개
  * 576px 이하: 1개
- [x] 디바이스 가로 길이가 768px 이하인 경우, 모달의 가로 길이를 디바이스 가로 길이만큼 늘려야 합니다.

#### 🔥TIP
* css 파일 하단에 mediaquery를 작성합니다. 분기 조건문을 `max-width` 로 작성합니다.
```css
@media (max-width: 992px) {
  .SearchResult {
    grid-template-columns: repeat(3, minmax(250px, 1fr));
  }
}
@media (max-width: 768px) {
  .SearchResult {
    grid-template-columns: repeat(2, minmax(250px, 1fr));
  }
}
@media (max-width: 576px) {
  .SearchResult {
    grid-template-columns: repeat(1, minmax(250px, 1fr));
  }
}
```

```css
@media (max-width: 12345px) { ... } -> 뷰포트 width가 12345px 이하인 경우 스타일링(최대 조건)
@media (min-width: 376px) { ... } -> 뷰포트 width가 376px 이상인 경우 스타일링(최소 조건

```

### 다크모드
- [x] 다크 모드(Dark mode)를 지원하도록 CSS를 수정해야 합니다.
  
  * CSS 파일 내의 다크 모드 관련 주석을 제거한 뒤 구현합니다.
  * 모든 글자 색상은 `#FFFFFF` , 배경 색상은 `#000000` 로 한정합니다.

#### 🔥TIP
* 기존 작성된 `prefers-color-scheme` 스펙을 확인합니다.
* 주석을 제거하고 결과를 확인합니다.
* 글자 색상, 배경 색상을 확인하면서 미션대로 수정합니다.
```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
    color: white;
  }
}
```

### 다크모드 토글
- [x] 기본적으로는 OS의 다크모드의 활성화 여부를 기반으로 동작하게 하되, 유저가 테마를 토글링 할 수 있도록 좌측 상단에 해당 기능을 토글하는 체크박스를 만듭니다.

#### 🔥TIP
* 참고 자료의 [The Complete Guide to the Dark Mode Toggle](https://ryanfeigenbaum.com/dark-mode/)를 참고하여 토글 버튼을 작성합니다.
* 방법1. input 이벤트 제어, DOM 제어, 로컬스토리지 사용법 등을 각각 학습하여 코드를 작성합니다.
* 방법2. 코드를 copy & paste하여 원하는 동작이 되는 정도만 작성합니다.

### 시맵틱 마크업(선택)
* (선택 미션입니다)
- [ ] 현재 HTML 코드가 전체적으로 `<div>` 로만 이루어져 있습니다. 이 마크업을 시맨틱한 방법으로 변경해야 합니다.
