### ISSUE TITLE
정사각형(1:1) 모양 만드는 트릭

### ISSUE THREAD

**Issue by ojj1123** [ojj1123/tip-archive#10]
```css
.outer {
  position: relative;
}

.outer:after {
  display: block;
  padding-bottom: 100%;
  content: "";
}

.inner {
  position: absolute;
  height: 100%;
  width: 100%;
}
```

```html
<div  class='outer'>
  <div class='inner'>
    ...
  </div>
</div>
```
