### ISSUE TITLE
@font-face 속성 중 unicode-range

### ISSUE THREAD

**Issue by ojj1123** [ojj1123/tip-archive#8]
```css
@font-face {
  font-family: 'MyWebFont'; /* Define the custom font name */
  src:  url('myfont.woff2') format('woff2'),
        url('myfont.woff') format('woff'); /* Define where the font can be downloaded */
  unicode-range: U+00-FF; /* Define the available characters */
}
```

> [**The important semantic distinction we should call out here is that unicode-range determines what characters a font can be used for, rather than what characters a font is available to use.** In other words, if we declare a unicode-range on @font-face and the characters that have loaded in an HTML document match that range, then the font will download and be put to use.](https://css-tricks.com/almanac/properties/u/unicode-range/#:~:text=The%20important%20semantic,put%20to%20use.)
> `unicode-range`는 폰트를 어떤 문자에 사용가능한지 보다는 폰트가 어떤 문자에 사용될 수 있는지를 의미함. 즉, HTML에 unicode-range에 지정한 문자가 나오면 해당 폰트를 다운받겠다는 의미 **(그 문자에만 폰트를 지정하겠다는 의미가 아님)**
